export const LOGIN = "LOGIN";

export const GET_LIST_ARTICLE = "GET_LIST_ARTICLE";
export const GET_LIST_ARTICLE_SUCCESS = "GET_LIST_ARTICLE_SUCCESS";
export const GET_LIST_ARTICLE_FAIL = "GET_LIST_ARTICLE_FAIL";

export const ADD_PRODUCT_REDUCER = "ADD_PRODUCT_REDUCER";
