export const LOGIN = "LOGIN";

export const GET_LIST_ARTICLE = "GET_LIST_ARTICLE";
export const GET_LIST_ARTICLE_SUCCESS = "GET_LIST_ARTICLE_SUCCESS";
export const GET_LIST_ARTICLE_FAIL = "GET_LIST_ARTICLE_FAIL";

export const GET_DETAIL_ARTICLE = "GET_DETAIL_ARTICLE";
export const GET_DETAIL_ARTICLE_SUCCESS = "GET_DETAIL_ARTICLE_SUCCESS";
export const GET_DETAIL_ARTICLE_FAIL = "GET_DETAIL_ARTICLE_FAIL";

export const GET_LENGTH_ARTICLE = "GET_LENGTH_ARTICLE";
export const GET_lENGTH_ARTICLE_SUCCESS = "GET_lENGTH_ARTICLE_SUCCESS";
export const GET_lENGTH_ARTICLE_FAIL = "GET_lENGTH_ARTICLE_FAIL";
